### PR TITLE
Bump the depended Jackson version to 2.15.3

### PR DESCRIPTION
**Pull request by dmikurube**
A fix in Jackson 2.15.3 is needed to enable this fix https://github.com/embulk/embulk-util-json/pull/33#issuecomment-1727651903 

https://github.com/FasterXML/jackson-core/pull/1111

It's time to upgrade the depended Jackson to the latest!

### CODE REVIEW

**Comment by dmikurube** [comment]
We may want to add a runtime check for the bundled Jackson version...?

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Added the runtime version check. :)

ecf37c3ab5517ed717c2c3e21f8362f56611ed70

**Comment by hiroyuki-sato** [comment]
runtime version check. LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
